<?php require_once './app/vista/vista.juegos.php';?>
<?php require_once './app/vista/vista.empresa.php';?>

<form action="agregar" method="POST" class="my-4">
    <label for="">Nombre Videojuego</label>
    <input type="text" name="nombre" id="nombre"> 

    <label for="">Genero</label>
    <input type="text" name="genero" id="genero">


    <div class="col-3">
            <div class="form-group">
                <label>Empresas</label>
                <select required name="id_empresa" class="form-control" id="id_empresa">
                    <?php foreach($empresa as $empresas):  ?>
                     <option value="<?= $empresas->id_empresa ?>"><?= $empresas->nombre ?></option>
                    <?php endforeach ?>
                </select>
            
            </div>
        </div>

    <button type="submit">Enviar</button>
</form>

               