<?php 
require 'templates/header.phtml';
?>

<h2>Login</h2>
<div>
    <form action="" method="POST">
        <label for="email">Email</label>
        <input type="email" required placeholder="ingrese email">

        <label for="password">Password</label>
        <input type="password" required placeholder="ingrese password">

        <?php if ($error) : ?>
            <div>
                <?= $error ?>
            </div>
        <?php endif ?>

        <button type="submit">Login</button>

    </form>
</div>

<?php require 'templates/footer.phtml' ?>
